#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

VERSION=""
ARM64_SHA=""
X86_64_SHA=""
TAP_DIR="${REPO_ROOT}/../homebrew-icevault"
REPO_OWNER=""
REPO_NAME=""

usage() {
  cat <<USAGE
Usage: ./scripts/update-homebrew-cask.sh [options]

Required:
  --version <version>        Release version without leading v (for example: 0.1.0)
  --arm64-sha <sha256>       SHA-256 for arm64 DMG
  --x86_64-sha <sha256>      SHA-256 for x86_64 DMG

Optional:
  --tap-dir <path>           Tap repository path (default: ../homebrew-icevault)
  --repo-owner <owner>       GitHub owner for release assets
  --repo-name <name>         GitHub repo name for release assets
  -h, --help                 Show help
USAGE
}

parse_owner_repo_from_origin() {
  local origin_url
  origin_url="$(git -C "${REPO_ROOT}" remote get-url origin 2>/dev/null || true)"
  if [[ -z "${origin_url}" ]]; then
    return 0
  fi

  if [[ "${origin_url}" =~ github.com[:/]([^/]+)/([^/.]+)(\.git)?$ ]]; then
    REPO_OWNER="${BASH_REMATCH[1]}"
    REPO_NAME="${BASH_REMATCH[2]}"
  fi
}

validate_sha() {
  local label="$1"
  local value="$2"
  if [[ ! "${value}" =~ ^[0-9a-fA-F]{64}$ ]]; then
    echo "Invalid ${label} SHA-256: ${value}" >&2
    exit 1
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --version)
      [[ $# -ge 2 ]] || { echo "Missing value for --version" >&2; exit 1; }
      VERSION="$2"
      shift 2
      ;;
    --arm64-sha)
      [[ $# -ge 2 ]] || { echo "Missing value for --arm64-sha" >&2; exit 1; }
      ARM64_SHA="$2"
      shift 2
      ;;
    --x86_64-sha)
      [[ $# -ge 2 ]] || { echo "Missing value for --x86_64-sha" >&2; exit 1; }
      X86_64_SHA="$2"
      shift 2
      ;;
    --tap-dir)
      [[ $# -ge 2 ]] || { echo "Missing value for --tap-dir" >&2; exit 1; }
      TAP_DIR="$2"
      shift 2
      ;;
    --repo-owner)
      [[ $# -ge 2 ]] || { echo "Missing value for --repo-owner" >&2; exit 1; }
      REPO_OWNER="$2"
      shift 2
      ;;
    --repo-name)
      [[ $# -ge 2 ]] || { echo "Missing value for --repo-name" >&2; exit 1; }
      REPO_NAME="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "${VERSION}" ]]; then
  echo "Missing required --version" >&2
  exit 1
fi

validate_sha "arm64" "${ARM64_SHA}"
validate_sha "x86_64" "${X86_64_SHA}"

if [[ -z "${REPO_OWNER}" || -z "${REPO_NAME}" ]]; then
  parse_owner_repo_from_origin
fi

if [[ -z "${REPO_OWNER}" || -z "${REPO_NAME}" ]]; then
  echo "Could not infer GitHub repo owner/name; pass --repo-owner and --repo-name" >&2
  exit 1
fi

if [[ "${TAP_DIR}" != /* ]]; then
  TAP_DIR="${REPO_ROOT}/${TAP_DIR}"
fi

CASK_DIR="${TAP_DIR}/Casks"
CASK_PATH="${CASK_DIR}/icevault.rb"

mkdir -p "${CASK_DIR}"

cat > "${CASK_PATH}" <<EOF_CASK
# This file is generated by IceVault release automation. DO NOT EDIT.
cask "icevault" do
  arch arm: "arm64", intel: "x86_64"

  version "${VERSION}"
  sha256 arm: "${ARM64_SHA}", intel: "${X86_64_SHA}"

  url "https://github.com/${REPO_OWNER}/${REPO_NAME}/releases/download/v#{version}/IceVault-#{version}-macos-#{arch}.dmg"
  name "IceVault"
  desc "Automated cold backups to AWS S3 Glacier Deep Archive"
  homepage "https://github.com/${REPO_OWNER}/${REPO_NAME}"

  depends_on macos: ">= :sonoma"

  app "IceVault.app"

  livecheck do
    url :url
    strategy :github_latest
  end
end
EOF_CASK

echo "Updated cask: ${CASK_PATH}"
